/**
 * Supporting Images Registry (Auto-generated)
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * This file is auto-generated by: npm run generate-images
 *
 * To add new images:
 * 1. Add your image files to: assets/supporting-images/
 * 2. Run: npm run generate-images
 *
 * Generated: 2025-12-27T16:33:41.210Z
 * Images found: 2
 */

const supportingImages = {
  'palette.jpg': require('../../assets/supporting-images/palette.jpg'),
  'topics.jpg': require('../../assets/supporting-images/topics.jpg'),
};

/**
 * Resolve a supporting image path to its bundled source.
 *
 * @param {string} imagePath - The image path from the schema (e.g., "palette.jpg")
 * @returns {number | { uri: string } | null} - The image source for React Native Image component
 */
export function resolveSupportingImage(imagePath) {
  if (!imagePath) return null;

  // If it's a remote URL, return as-is in uri format
  if (imagePath.startsWith('http://') || imagePath.startsWith('https://')) {
    return { uri: imagePath };
  }

  // Look up in registry
  const source = supportingImages[imagePath];
  if (source) {
    return source;
  }

  // Try with just the filename (in case path includes directories)
  const filename = imagePath.split('/').pop();
  if (filename && supportingImages[filename]) {
    return supportingImages[filename];
  }

  console.warn(`Supporting image not found in registry: ${imagePath}. Run 'npm run generate-images' to update.`);
  return null;
}

/**
 * Get all registered image paths
 */
export function getRegisteredImages() {
  return Object.keys(supportingImages);
}

export default supportingImages;
